"""add service due tracking

Revision ID: ad361ba70c18
Revises: 8328ebf007dd
Create Date: 2026-09-03 01:40:57.014296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad361ba70c18'
down_revision: Union[str, Sequence[str], None] = '8328ebf007dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('service_due_since', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'service_due_since')
    # ### end Alembic commands ###
